import { setTashkentTime } from "../../utils"

export const transactionsColumns = (pageNumber, pageSize) => [
    {
        title: `#`,
        key: 'numberOfRow',
        fixed: 'left',
        align: 'center',
        width: 60,
        render: (text, obj, index) => {
            return (
                <span> {(pageNumber - 1) * pageSize + index + 1} </span>
            )
        },
        checked: true,
    },
    {
        title: `Card Number`,
        dataIndex: ['transaction', 'cardNumber'],
        key: 'cardNumber',
        align: 'center',
        width: 200,
        checked: true,
    },
    {
        title: `Transaction Date`,
        dataIndex: ['transaction', 'transactionDate'],
        key: 'transactionDate',
        align: 'center',
        width: 150,
        checked: true,
        render: (date) => <>{date ? setTashkentTime(date, 'YYYY-MM-DD') : null}</>
    },
    {
        title: `Unit`,
        dataIndex: ['transaction', 'unit'],
        key: 'unit',
        align: 'center',
        width: 100,
        checked: true,
    },
    {
        title: `Driver Name`,
        dataIndex: ['transaction', 'driverName'],
        key: 'driverName',
        align: 'center',
        width: 200,
        checked: true,
    },
    {
        title: `Location Name`,
        dataIndex: ['transaction', 'locationName'],
        key: 'locationName',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `City`,
        dataIndex: ['transaction', 'city'],
        key: 'city',
        align: 'center',
        width: 100,
        checked: true,
    },
    {
        title: `State`,
        dataIndex: ['transaction', 'state'],
        key: 'state',
        align: 'center',
        width: 100,
        checked: true,
    },
    {
        title: `Fees`,
        dataIndex: ['transaction', 'fees'],
        key: 'fees',
        align: 'center',
        width: 100,
        checked: true,
    },
    {
        title: `Item`,
        dataIndex: ['transaction', 'item'],
        key: 'item',
        align: 'center',
        width: 100,
        checked: true,
    },
    {
        title: `Unit Price`,
        dataIndex: ['transaction', 'unitPrice'],
        key: 'unitPrice',
        align: 'center',
        width: 100,
        checked: true,
    },
    {
        title: `Disc PPU`,
        dataIndex: ['transaction', 'discPpu'],
        key: 'discPpu',
        align: 'center',
        width: 100,
        checked: true,
    },
    {
        title: `Disc Cost`,
        dataIndex: ['transaction', 'discCost'],
        key: 'discCost',
        align: 'center',
        width: 100,
        checked: true,
    },
    {
        title: `State`,
        dataIndex: ['transaction', 'state'],
        key: 'state',
        align: 'center',
        width: 100,
        checked: true,
    },
    {
        title: `Quantity`,
        dataIndex: ['transaction', 'quantity'],
        key: 'quantity',
        align: 'center',
        width: 100,
        checked: true,
    },
    {
        title: `Disc Amount`,
        dataIndex: ['transaction', 'discAmount'],
        key: 'discAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `Amount`,
        dataIndex: ['transaction', 'amount'],
        key: 'amount',
        align: 'center',
        width: 100,
        checked: true,
    },
    {
        title: `Currency`,
        dataIndex: ['transaction', 'currency'],
        key: 'currency',
        align: 'center',
        width: 150,
        checked: true,
    },
]