import { translations } from "../../translations";
import { t } from "../../utils/transliteration";

export const transactionsGroupsColumns = (pageNumber, pageSize, language = 'en') => [
    {
        title: `#`,
        key: 'numberOfRow',
        fixed: 'left',
        align: 'center',
        width: 60,
        render: (text, obj, index) => {
            return (
                <span> {(pageNumber - 1) * pageSize + index + 1} </span>
            )
        },
        checked: true,
    },
    {
        title: t(translations, 'driverName', language),
        dataIndex: 'driverName',
        key: 'driverName',
        align: 'center',
        width: 200,
        checked: true,
    },
    {
        title: t(translations, 'ulsdQuantity', language),
        dataIndex: 'ulsdQuantity',
        key: 'ulsdQuantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'defdQuantity', language),
        dataIndex: 'defdQuantity',
        key: 'defdQuantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'cadvQuantity', language),
        dataIndex: 'cadvQuantity',
        key: 'cadvQuantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'cdslQuantity', language),
        dataIndex: 'cdslQuantity',
        key: 'cdslQuantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'dsl1Quantity', language),
        dataIndex: 'dsl1Quantity',
        key: 'dsl1Quantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'fuelQuantity', language),
        dataIndex: 'fuelQuantity',
        key: 'fuelQuantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'scleQuantity', language),
        dataIndex: 'scleQuantity',
        key: 'scleQuantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'staxQuantity', language),
        dataIndex: 'staxQuantity',
        key: 'staxQuantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'ulsrQuantity', language),
        dataIndex: 'ulsrQuantity',
        key: 'ulsrQuantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'ulsdAmount', language),
        dataIndex: 'ulsdAmount',
        key: 'ulsdAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'defdAmount', language),
        dataIndex: 'defdAmount',
        key: 'defdAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'cadvAmount', language),
        dataIndex: 'cadvAmount',
        key: 'cadvAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'cdslAmount', language),
        dataIndex: 'cdslAmount',
        key: 'cdslAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'dsl1Amount', language),
        dataIndex: 'dsl1Amount',
        key: 'dsl1Amount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'fuelAmount', language),
        dataIndex: 'fuelAmount',
        key: 'fuelAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'scleAmount', language),
        dataIndex: 'scleAmount',
        key: 'scleAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'staxAmount', language),
        dataIndex: 'staxAmount',
        key: 'staxAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'ulsrAmount', language),
        dataIndex: 'ulsrAmount',
        key: 'ulsrAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'discountAmount', language),
        dataIndex: 'discountAmount',
        key: 'discountAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'feesAmount', language),
        dataIndex: 'feesAmount',
        key: 'feesAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'totalAmount', language),
        dataIndex: 'totalAmount',
        key: 'totalAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
]