export const transactionsGroupsColumns = (pageNumber, pageSize) => [
    {
        title: `#`,
        key: 'numberOfRow',
        fixed: 'left',
        align: 'center',
        width: 60,
        render: (text, obj, index) => {
            return (
                <span> {(pageNumber - 1) * pageSize + index + 1} </span>
            )
        },
        checked: true,
    },
    {
        title: `Driver Name`,
        dataIndex: 'driverName',
        key: 'driverName',
        align: 'center',
        width: 200,
        checked: true,
    },
    {
        title: `ULSD Quantity`,
        dataIndex: 'ulsdQuantity',
        key: 'ulsdQuantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `DEFD Quantity`,
        dataIndex: 'defdQuantity',
        key: 'defdQuantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `CADV Quantity`,
        dataIndex: 'cadvQuantity',
        key: 'cadvQuantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `CDSL Quantity`,
        dataIndex: 'cdslQuantity',
        key: 'cdslQuantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `DSL1 Quantity`,
        dataIndex: 'dsl1Quantity',
        key: 'dsl1Quantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `FUEL Quantity`,
        dataIndex: 'fuelQuantity',
        key: 'fuelQuantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `SCLE Quantity`,
        dataIndex: 'scleQuantity',
        key: 'scleQuantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `STAX Quantity`,
        dataIndex: 'staxQuantity',
        key: 'staxQuantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `ULSR Quantity`,
        dataIndex: 'ulsrQuantity',
        key: 'ulsrQuantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `ULSD Amount`,
        dataIndex: 'ulsdAmount',
        key: 'ulsdAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `DEFD Amount`,
        dataIndex: 'defdAmount',
        key: 'defdAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `CADV Amount`,
        dataIndex: 'cadvAmount',
        key: 'cadvAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `CDSL Amount`,
        dataIndex: 'cdslAmount',
        key: 'cdslAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `DSL1 Amount`,
        dataIndex: 'dsl1Amount',
        key: 'dsl1Amount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `FUEL Amount`,
        dataIndex: 'fuelAmount',
        key: 'fuelAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `SCLE Amount`,
        dataIndex: 'scleAmount',
        key: 'scleAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `STAX Amount`,
        dataIndex: 'staxAmount',
        key: 'staxAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `ULSR Amount`,
        dataIndex: 'ulsrAmount',
        key: 'ulsrAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `Discount Amount`,
        dataIndex: 'discountAmount',
        key: 'discountAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `Fees`,
        dataIndex: 'feesAmount',
        key: 'feesAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `Total`,
        dataIndex: 'totalAmount',
        key: 'totalAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
]