import { setUTCTime } from "../../utils";

export const uncheckedTransactionsColumns = (pageNumber, pageSize) => [
    {
        title: `#`,
        key: 'numberOfRow',
        fixed: 'left',
        align: 'center',
        width: 60,
        render: (text, obj, index) => {
            return (
                <span> {(pageNumber - 1) * pageSize + index + 1} </span>
            )
        },
        checked: true,
    },
    {
        title: `Transaction Date`,
        dataIndex: 'transactionDate',
        key: 'transactionDate',
        type: 'string',
        align: 'center',
        width: 150,
        checked: true,
        render: (transactionDate) => setUTCTime(transactionDate, 'YYYY-MM-DD')
    },
    {
        title: `Driver Name`,
        dataIndex: 'driverName',
        key: 'driverName',
        align: 'center',
        width: 200,
        checked: true,
    },
    {
        title: `File Name`,
        dataIndex: 'fileName',
        key: 'fileName',
        align: 'center',
        width: 200,
        checked: true,
    },
    {
        title: `Card Number`,
        dataIndex: 'cardNumber',
        key: 'cardNumber',
        align: 'center',
        width: 200,
        checked: true,
    },
    {
        title: `Invoice Number`,
        dataIndex: 'invoiceNumber',
        key: 'invoiceNumber',
        align: 'center',
        width: 200,
        checked: true,
    },
    {
        title: `Unit Price`,
        dataIndex: 'unitPrice',
        key: 'unitPrice',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `Fees`,
        dataIndex: 'fees',
        key: 'fees',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `Discount PPU`,
        dataIndex: 'discPpu',
        key: 'discPpu',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `Discount Cost`,
        dataIndex: 'discCost',
        key: 'discCost',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `Quantity`,
        dataIndex: 'quantity',
        key: 'quantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `Discount Amount`,
        dataIndex: 'discAmount',
        key: 'discAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `Discount Type`,
        dataIndex: 'discType',
        key: 'discType',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `Amount`,
        dataIndex: 'amount',
        key: 'amount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `DB`,
        dataIndex: 'db',
        key: 'db',
        align: 'center',
        width: 100,
        checked: true,
    },
    {
        title: `Currency`,
        dataIndex: 'currency',
        key: 'currency',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `Odometer`,
        dataIndex: 'odometer',
        key: 'odometer',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `State`,
        dataIndex: 'state',
        key: 'state',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `City`,
        dataIndex: 'city',
        key: 'city',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: `Location`,
        dataIndex: 'locationName',
        key: 'locationName',
        align: 'center',
        width: 300,
        checked: true,
    },
]