import { setUTCTime } from "../../utils";
import { translations } from "../../translations";
import { t } from "../../utils/transliteration";

export const uncheckedTransactionsColumns = (pageNumber, pageSize, language = 'en') => [
    {
        title: `#`,
        key: 'numberOfRow',
        fixed: 'left',
        align: 'center',
        width: 60,
        render: (text, obj, index) => {
            return (
                <span> {(pageNumber - 1) * pageSize + index + 1} </span>
            )
        },
        checked: true,
    },
    {
        title: t(translations, 'transactionDate', language),
        dataIndex: 'transactionDate',
        key: 'transactionDate',
        type: 'string',
        align: 'center',
        width: 150,
        checked: true,
        render: (transactionDate) => setUTCTime(transactionDate, 'YYYY-MM-DD')
    },
    {
        title: t(translations, 'driverName', language),
        dataIndex: 'driverName',
        key: 'driverName',
        align: 'center',
        width: 200,
        checked: true,
    },
    {
        title: t(translations, 'fileName', language),
        dataIndex: 'fileName',
        key: 'fileName',
        align: 'center',
        width: 200,
        checked: true,
    },
    {
        title: t(translations, 'cardNumber', language),
        dataIndex: 'cardNumber',
        key: 'cardNumber',
        align: 'center',
        width: 200,
        checked: true,
    },
    {
        title: t(translations, 'invoiceNumber', language),
        dataIndex: 'invoiceNumber',
        key: 'invoiceNumber',
        align: 'center',
        width: 200,
        checked: true,
    },
    {
        title: t(translations, 'unitPrice', language),
        dataIndex: 'unitPrice',
        key: 'unitPrice',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'fees', language),
        dataIndex: 'fees',
        key: 'fees',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'discPpu', language),
        dataIndex: 'discPpu',
        key: 'discPpu',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'discCost', language),
        dataIndex: 'discCost',
        key: 'discCost',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'quantity', language),
        dataIndex: 'quantity',
        key: 'quantity',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'discAmount', language),
        dataIndex: 'discAmount',
        key: 'discAmount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'discType', language),
        dataIndex: 'discType',
        key: 'discType',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'amount', language),
        dataIndex: 'amount',
        key: 'amount',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'db', language),
        dataIndex: 'db',
        key: 'db',
        align: 'center',
        width: 100,
        checked: true,
    },
    {
        title: t(translations, 'currency', language),
        dataIndex: 'currency',
        key: 'currency',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'odometer', language),
        dataIndex: 'odometer',
        key: 'odometer',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'state', language),
        dataIndex: 'state',
        key: 'state',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'city', language),
        dataIndex: 'city',
        key: 'city',
        align: 'center',
        width: 150,
        checked: true,
    },
    {
        title: t(translations, 'locationName', language),
        dataIndex: 'locationName',
        key: 'locationName',
        align: 'center',
        width: 300,
        checked: true,
    },
]